-- You can add your own plugins here or in other files in this directory!
--  I promise not to create any merge conflicts in this directory :)
--
-- See the kickstart.nvim README for more information
return {}
-- return {
--   {
--     'stevearc/oil.nvim',
--     ---@module 'oil'
--     ---@type oil.SetupOpts
--     opts = {},
--     -- Optional dependencies
--     dependencies = { { 'echasnovski/mini.icons', opts = {} } },
--     -- dependencies = { "nvim-tree/nvim-web-devicons" }, -- use if you prefer nvim-web-devicons
--     -- Lazy loading is not recommended because it is very tricky to make it work correctly in all situations.
--     lazy = false,
--   },
--   {
--     'ThePrimeagen/harpoon',
--     branch = 'harpoon2',
--     dependencies = { 'nvim-lua/plenary.nvim' },
--     init = function()
--       local harpoon = require 'harpoon'
--       -- vim.keymap.set('n', '<leader><leader>', builtin.buffers, { desc = '[ ] Find existing buffers' })
--
--       vim.keymap.set('n', '<leader>a', function()
--         harpoon:list():add()
--       end, { desc = '[A]dd file to harpoon' })
--       vim.keymap.set('n', '<C-e>', function()
--         harpoon.ui:toggle_quick_menu(harpoon:list())
--       end)
--
--       vim.keymap.set('n', '<leader>1', function()
--         harpoon:list():select(1)
--       end, { desc = 'Select [1]st harpooned' })
--       vim.keymap.set('n', '<leader>2', function()
--         harpoon:list():select(2)
--       end, { desc = 'Select [2]nd harpooned' })
--       vim.keymap.set('n', '<leader>3', function()
--         harpoon:list():select(3)
--       end, { desc = 'Select [3]rd harpooned' })
--       vim.keymap.set('n', '<leader>4', function()
--         harpoon:list():select(4)
--       end, { desc = 'Select [4]th harpooned' })
--     end,
--   },
-- }
